name: Build SunamoTypes

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoTypes
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoTypes/SunamoTypes.csproj

    - name: Build
      run: dotnet build SunamoTypes/SunamoTypes.csproj --configuration Release --no-restore

  test:
    name: Test SunamoTypes.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoTypes.Tests/SunamoTypes.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoTypes.Tests/SunamoTypes.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoTypes.Tests/SunamoTypes.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
